# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - qiqibook

on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x' # set this to the node version to use
  AZURE_WEBAPP_NAME: qiqibook 
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: list output
        run: |
          ls
      - name: Zip artifact for deployment
        run: zip release.zip ./build/* -r 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
   
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - name: unzip artifact for deployment
        run: unzip release.zip
      - name: 'Deploy to Azure WebApp'
       
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          
          publish-profile: ${{ secrets.QIQIBOOK_WEB_APP }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  